name: Deploy the backend

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: ansh7845/excalidraw-backend
  DOMAIN: excalidraw.anshtyagi.me
  DROPLET_IP: 142.93.223.72

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/docker.backend
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy to the VM
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@${{ env.DROPLET_IP }} -t "
            docker stop excalidraw-backend || true
            docker rm excalidraw-backend || true
            docker run --name excalidraw-backend -d -p 3001:3001 \
              -e DATABASE_URL='${{ secrets.DATABASE_URL }}' \
              ${{ env.IMAGE_NAME }}:${{ github.sha }}
          "
